LOCAL_PATH:= $(call my-dir)
PARTITION=system
VENDOR_PATH=system/vendor
IS_ANDROID9=false
IS_BUILD_VENDOR_MODULE=false
ifeq (1,$(filter 1,$(shell echo "$$(( $(PLATFORM_SDK_VERSION) >= 26 ))" )))
   PARTITION=vendor
   VENDOR_PATH=vendor
   IS_ANDROID9=true
   IS_BUILD_VENDOR_MODULE=true
endif

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libVmiInstructionEngine
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES_arm :=${PARTITION}/lib/libVmiInstructionEngine.so
LOCAL_SRC_FILES_arm64 :=${PARTITION}/lib64/libVmiInstructionEngine.so
LOCAL_MODULE_TARGET_ARCHS:= arm arm64
LOCAL_VENDOR_MODULE := ${IS_BUILD_VENDOR_MODULE}
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libVmiCommonInstr
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES_arm :=${PARTITION}/lib/libVmiCommonInstr.so
LOCAL_SRC_FILES_arm64 :=${PARTITION}/lib64/libVmiCommonInstr.so
LOCAL_MODULE_TARGET_ARCHS:= arm arm64
LOCAL_VENDOR_MODULE := ${IS_BUILD_VENDOR_MODULE}
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libVmiUtil
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES_arm :=${PARTITION}/lib/libVmiUtil.so
LOCAL_SRC_FILES_arm64 :=${PARTITION}/lib64/libVmiUtil.so
LOCAL_MODULE_TARGET_ARCHS:= arm arm64
LOCAL_VENDOR_MODULE := ${IS_BUILD_VENDOR_MODULE}
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)
